version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/cicddemo.jar
  discard-paths: yes